export const defaultWords = [
  "Handdoeke",
  "Badmatjie",
  "Laken",
  "Pas laken",
  "Kussing slope",
  "Vaddoeke",
  "Waslappe",
  "Sout potjie",
  "Peper potjie",
  "Asyn houer",
  "Olie houer",
  "Koek pan",
  "Muffin pan",
  "Brood pan",
  "Ys houer",
  "Messe",
  "Vurke",
  "Lepels",
  "Tee koppies",
  "Tee pot",
  "Tee lepels",
  "Koek staander",
  "Glase",
  "Wit wyn glase",
  "Rooi wyn glase",
  "Whiskey glase",
  "Tupperware",
  "Koek roller",
  "Waspoeier houer",
  "Koek blik",
  "Koffie bekers",
  "Tee koppie",
  "Sny bord",
  "Hour bord",
  "Kaas bord",
  "Kaas Mes",
  "Sop lepel",
  "Mash drukker",
  "Sker",
  "Spatula",
  "Kaas snyer",
  "Rasper",
  "Sif",
  "Maatbeker",
  "Maat lepels",
  "Mandjies",
  "Caserole",
  "Cake lifter",
  "Op-skep bakke",
  "Tert bak",
  "Koffie houer",
  "Tee houer",
  "Kerse",
  "Plantjies",
  "Handy Andy",
  "Waspoeier",
  "Sunlight Liquid",
  "Doom",
  "Speserye",
  "Blompot",
  "Kussings",
  "Lekker ruik stokkies",
  "Houtlepel",
  "Borde",
  "Klein bordjies",
  "Bakkies",
  "Sop Bakkies",
  "Melk beker",
  "Suiker pot",
];
